# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "./alpine-3.2.3.box"
  config.vm.hostname = "alpine"
  config.vm.synced_folder "./", "/vagrant"
  config.vm.network "private_network", type: "dhcp"

  config.ssh.shell = "ash"

  config.dns.tld = "development.beardandcode.com"
end
